### ISSUE TITLE
Is the license really necessary?

### ISSUE THREAD

**Issue by SpeedyMouse76** [structureio/sample-scanner#11]
Do I need a license key to run the sample app, or does the app work without licenses? If the app works without licenses, what limitations do I have then?

**Comment by a-tokar** [comment]
Hello!

The app itself is open source and free to use, however, it depends on Structure SDK which has advanced paid features. So, it depends on what features you're interested in. For instance, streaming data from Structure Sensor Pro is free, but object reconstruction is not.

**Comment by SpeedyMouse76** [comment]
Ok, did you have a link, where describe what kind of features are useable for free and for which features I need the license ?

**Comment by a-tokar** [comment]
Unfortunately, this is under construction, but here is the list of paid features at this moment:
* Support for 3rd-party sensors: Apple TrueDepth and Apple LiDAR
* Extended support for ST01 sensor
* Object reconstruction capabilities (including tracking and mapping)
* Colorization/Texturing
* Scan Quality Indicator
