### ISSUE TITLE
Scanner apps requires SDK license

### ISSUE THREAD

**Issue by carlosoleto** [structureio/sample-scanner#8]
We have been using the Scanner app on iPad, and today, it is failing, requiring an SDK license to run.

Looking at the repository and on the support page, I couldn't find any way to provide this license, and it appears that we already have one since we own a scanner.

It appears something like that in the Readme, but it would require building it from the source.

How can we return using the Scanner App from the Applet App Store?

**Comment by kazi-mifta** [comment]
@carlosoleto please get in touch with our support team to resolve issues like this: support@structure.io. I think turning on the internet will resolve your issue as the "license check" requires an internet connection. But if your problem persists, please feel free to contact the support team and they will be very happy to help you out.
