### ISSUE TITLE
dyld[2207]: Library not loaded: @rpath/Structure.framework/Structure

### ISSUE THREAD

**Issue by alamboley** [structureio/sample-scanner#9]
Hello,

I've added the SDK but it fails on start on mobile:
<img width="748" alt="Capture d’écran 2024-01-24 à 15 58 03" src="https://github.com/structureio/sample-scanner/assets/687978/20806d2a-b0a4-4878-930a-73623a56f059">
<img width="931" alt="Capture d’écran 2024-01-24 à 15 58 18" src="https://github.com/structureio/sample-scanner/assets/687978/812147c8-c559-429e-847e-892d5c0f0658">
```
dyld[2207]: Library not loaded: @rpath/Structure.framework/Structure
  Referenced from: <56079A00-72F9-39C4-90DC-23E98E1986C1> /private/var/containers/Bundle/Application/33D3E5EA-A3EA-4402-82E1-86FF7CDBF776/Scanner.app/Scanner
  Reason: tried: '/usr/lib/swift/Structure.framework/Structure' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Structure.framework/Structure' (no such file), '/private/var/containers/Bundle/Application/33D3E5EA-A3EA-4402-82E1-86FF7CDBF776/Scanner.app/Frameworks/Structure.framework/Structure' (no such file), '/usr/lib/swift/Structure.framework/Structure' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Structure.framework/Structure' (no such file), '/private/var/containers/Bundle/Application/33D3E5EA-A3EA-4402-82E1-86FF7CDBF776/Scanner.app/Frameworks/Structure.framework/Structure' (no such file)
```

What I'm missing?

**Comment by a-tokar** [comment]
Hello!

Thanks for reaching out.

Please make sure that the "Embed Frameworks" option is enabled in the "Build Phases" section:
<img width="672" alt="image" src="https://github.com/structureio/sample-scanner/assets/24511970/f6acc788-c073-4731-8e19-fbc02ba5e498">
Also, check that Structure Framework is present in the built app: `Scanner.app/Frameworks/Structure.framework`
